# Generated by Django 4.1.1 on 2022-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=25, null=True)),
                ('course', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
