# Generated by Django 4.1.1 on 2022-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='')),
                ('course_image', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
