# Generated by Django 4.1.1 on 2022-10-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_gradefive_gradefour_gradeone_gradeseven_gradesix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeeight',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradefive',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradefour',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeone',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeseven',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradesix',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradethree',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradetwo',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradeeight',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradeeight',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradeeight',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradefive',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradefive',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradefive',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradefour',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradefour',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradefour',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradeone',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradeone',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradeone',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradeseven',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradeseven',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradeseven',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradesix',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradesix',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradesix',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradethree',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradethree',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradethree',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='gradetwo',
            name='course_image',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
        migrations.AlterField(
            model_name='gradetwo',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradetwo',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
    ]
