# Generated by Django 4.1.1 on 2022-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_course_category_gradeeight_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradeeight',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradefive',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradefour',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradeone',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradeseven',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradesix',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradethree',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gradetwo',
            name='category',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True),
        ),
    ]
