# Generated by Django 4.1.1 on 2022-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_course_category_alter_gradeeight_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=6, null=True),
        ),
    ]
